"""Add tasks table

Revision ID: f4c81af9a9ba
Revises: 
Create Date: 2025-11-22 10:15:03.453537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f4c81af9a9ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_metadata', sa.JSON(), nullable=True))
    op.drop_column('tasks', 'tasmetadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tasmetadata', sqlite.JSON(), nullable=True))
    op.drop_column('tasks', 'task_metadata')
    # ### end Alembic commands ###
